config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products do
  	resources :rates
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :rates
	validates :title, presence: true
	validates :description, presence: true
  validate :end_date_cant_be_in_past, :start_date_cant_be_past_end_date

  scope :active, -> { where("end_date > DATETIME('now')") }

  def end_date_cant_be_in_past
		if end_date.present? && end_date < Date.today
			errors.add(:end_date, "Can't be in the past")
		end
	end

	def start_date_cant_be_past_end_date
		if start_date.present? && end_date.present? && start_date > end_date
			errors.add(:start_date, "Can't be later than end date")
		end
	end
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :product
  validates :price, numericality: { greater_than: 0 }
  validate :end_date_cant_be_in_past, :start_date_cant_be_past_end_date

  def end_date_cant_be_in_past
		if end_date.present? && end_date < Date.today
			errors.add(:end_date, "Can't be in the past")
		end
	end

	def start_date_cant_be_past_end_date
		if start_date.present? && end_date.present? && start_date > end_date
			errors.add(:start_date, "Can't be later than end date")
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@product = Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def index
		@products = Product.all
		@active_products = Product.active
		respond_to do |format|
			format.html
			format.json { render json: @active_products }
		end
	end

	def show
		@product = Product.find(params[:id])
		respond_to do |format|
			format.html
			if @product.end_date > Date.today
				format.json { render json: @product }
			else
				format.json { render json: {}}
			end
		end
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to @product
		else 
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to products_path
	end

	private
		def product_params
			params.require(:product).permit(:title, :description, :start_date, :end_date)
		end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
		@rate = @product.rates.create(rate_params)
		redirect_to product_path(@product)
	end

	def update
		@product = Product.find(params[:product_id])
		@rate = @product.rates.find(params[:id])
		@rate.update(rate_params)
		redirect_to product_path(@product)

	end

	def destroy
		@product = Product.find(params[:product_id])
		@rate = @product.rates.find(params[:id])
		@rate.destroy
		redirect_to product_path(@product)
	end

	private
		def rate_params
			params.require(:rate).permit(:title, :description, :start_date, :end_date, :recurrence, :price)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductCatalog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= bootstrap_form_for(@product) do |f| %>



	<%= f.text_field :title %>

	<%= f.text_area :description %>

	<%= f.date_select :start_date %>

	<%= f.date_select :end_date %>
	<%= f.submit "Create" %>
			 
<% end %>

app/views/products/edit.html.erb
<html>
	<body>
		<div class="container">
			<h1>Edit Product
						<div class="btn-group">
			<%= link_to 'Back', products_path, :class => "btn btn-default" %>
			</div>
			</h1>

			<%= render 'form' %>
		</div>
	</body>
</html>

app/views/products/index.html.erb
<html>

	<body>

		<div class="container">
			<h1>Product Catalog</h1>

			<div class="btn-group">
			<%= link_to 'New Product', new_product_path, :class => "btn btn-default" %>
			</div>

			<table class="table table-hover table-responsive">
				<thead>
					<tr>
						<th>Title</th>
						<th>Description</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @products.each do |product| %>
					<tr>
						<td><%= product.title %></td>
						<td><%= product.description %></td>
						<td><%= product.start_date %></td>
						<td><%= product.end_date %></td>
						<td>
						<div class="btn-group">
						<%= link_to 'View', product_path(product), :class => "btn btn-info" %>
						<%= link_to 'Edit', edit_product_path(product), :class => "btn btn-success" %>
						<%= link_to 'Discontinue', product_path(product, :product => {:end_date => Date.today.to_s}),
							method: :put,
							data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
						</div>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</body>
</html>

app/views/products/new.html.erb
<html>
	<body>
		<div class="container">
			<h1>New Product
						<div class="btn-group">
			<%= link_to 'Back', products_path, :class => "btn btn-default" %>
			</div>
			</h1>

			<%= render 'form' %>
		</div>
	</body>
</html>

app/views/products/show.html.erb
<html>
	<body>
		<div class="container">

		<h1>Product <%= @product.title %></h1>

			<div class="btn-group">
			<%= link_to 'Back', products_path, :class => "btn btn-default" %>
			</div>

			<table class="table table-responsive">
				<thead>
					<tr>
						<th>Title</th>
						<th>Description</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<td><%= @product.title %></td>
					<td><%= @product.description %></td>
					<td><%= @product.start_date %></td>
					<td><%= @product.end_date %></td>
					<td>
					<div class="btn-group">
				<%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-success" %>
				<% if defined? @product.end_date && @product.end_date > Date.today %>
				<%= link_to 'Discontinue', product_path(@product, :product => {:end_date => Date.today.to_s}),
					method: :put,
					data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
					<% end %>
			</div>
					</td>
				</tbody>
			</table>
		</div>
		<div class="container">
			<h1>Rates</h1>
			<table class="table">
				<thead>
					<tr>
						<th>Title</th>
						<th>Description</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Recurrence</th>
						<th>Price</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @product.rates.each do |rate| %>
					<tr>
						<td><%= rate.title %></td>
						<td><%= rate.description %></td>
						<td><%= rate.start_date %></td>
						<td><%= rate.end_date %></td>
						<td><%= rate.recurrence %></td>
						<td><%= number_to_currency(rate.price) %></td>
						<td>
						<div class="btn-group">
							<%= link_to 'Discontinue', product_rate_path(@product, rate, :rate => {:end_date => Date.today.to_s}),
							method: :put,
							data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
						</div>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="container">
			<h2>Add new rate</h2>
			<%= render 'rates/form' %>
		</div>
	</body>
</html>

app/views/rates/_form.html.erb
<%= bootstrap_form_for([@product, @product.rates.build], layout: :horizontal) do |f| %>

		<%= f.text_field :title %>

		<%= f.text_area :description %>

			<%= f.date_select :start_date %>
			<%= f.date_select :end_date %>

		<%= f.select :recurrence, ["One-time", "Monthly", "Quarterly", "Annually"], {label: "How often?" }, { class: "selectpicker"} %>

		<%= f.text_field :price,  prepend: "$" %>

		<%= f.submit "Add New Rate" %>
	 
<% end %>

app/views/rates/_rate.html.erb
<tr>
	<td><%= rate.title %></td>
	<td><%= rate.description %></td>
	<td><%= rate.start_date %></td>
	<td><%= rate.end_date %></td>
	<td><%= rate.recurrence %></td>
	<td>$<%= number_to_currency(rate.price)f %></td>
	<td>
	<div class="btn-group">
		<%= link_to 'Edit', edit_product_rate_path(product, rate), :class => "btn btn-default" %>
		<%= link_to 'Delete', product_rate_path(product, rate),
			method: :delete,
			data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>
	</div>
	</td>
</tr>

app/views/rates/edit.html.erb
<h1>Edit Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<h1>Products</h1>
<%= link_to 'Product Catalog', controller: 'products' %>